### PR TITLE
Update tasks in publish.yml

### PR DESCRIPTION
**Pull request by sliiser**

### CODE REVIEW

**Review by aronglia — APPROVED** [review]
Looks good.

One thing I would mention is that it is better to lock down the used action to a specific commit like we had before. In case the `discourse/publish-rubygems-action` repository is compromised, and someone is able to push new `v2` version then we are not affected as we are still using the version we have manually confirmed is legit.

**Comment by sliiser** [comment]
!squash

**Comment by sliiser** [comment]
!merge

**Comment by sliiser** [comment]
!merge

**Pull request merged**
